import { useEffect,useRef } from 'react'
import { createPortal } from 'react-dom'

export default function CanvasProductionDialog({quote,busy,onCancel,onConfirm}){
  const ref=useRef(null)
  useEffect(()=>{const prior=document.activeElement;ref.current?.querySelector('button')?.focus();const key=e=>{if(e.key==='Escape'&&!busy)onCancel();if(e.key==='Tab'){const buttons=ref.current?.querySelectorAll('button:not(:disabled)');if(!buttons?.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);prior?.focus?.()}},[busy,onCancel])
  const money=n=>`€${(n/100).toFixed(2)}`
  return createPortal(<div className="cg-modal-backdrop"><section className="cg-modal" ref={ref} role="dialog" aria-modal="true" aria-label="Confirm Canvas production"><h3>Run {quote.outputCount} output(s) · {money(quote.totalMinor)}</h3><p>This exact frozen path uses M5. One submission attempt per Job; no automatic generation retry.</p><ol>{quote.steps.map(s=><li key={s.id}><strong>{s.model}</strong> · {s.capability==='generate_image'?s.params.image_size:`${s.params.seconds}s · ${s.params.resolution} · ${s.params.aspect_ratio}`}<br/><small>{s.dependencies.length?'Uses output 1 of its upstream image Job.':s.params.start_frame?'Uses the selected local start frame.':'Uses the shown prompt and selected inputs.'}</small></li>)}</ol><p>New reservation ceiling: <strong>{money(quote.totalMinor)}</strong>. Catalog estimate, not a verified invoice. Image cents round up per Job. Missing FX or budget blocks dispatch.</p><p>Regeneration needs a fresh quote. Submitted requests cannot be undone or refunded by editing the board.</p><div className="cg-actions"><button className="ghost" disabled={busy} onClick={onCancel}>Cancel</button><button className="primary" disabled={busy} onClick={onConfirm}>Confirm Canvas generation</button></div></section></div>,document.body)
}
