import { useRef, useState } from 'react'
import { apiBase } from '../lib/ai/apiClient.js'
import './ReferenceRemix.css'

export const remixModes = [['product_swap','Product / Object Swap'],['character_swap','Character / Creator Swap'],['background_swap','Background / Location Swap'],['outfit','Outfit / Appearance'],['motion_transfer','Motion Transfer'],['full_remix','Full Ad Remix']]
const roles=['PRODUCT','PACKAGING','CHARACTER','OUTFIT','BACKGROUND','LOCATION','APP_SCREEN','STYLE','OTHER']
const keepOptions=['Camera movement','Timing / pacing','Scene order','Creator','Background','Lighting style','Visual style','Audio structure']
const analysisFields=[['setting','Setting'],['subject','Subject / creator'],['product','Visible product'],['shotTypes','Shot types'],['camera','Camera behavior'],['lighting','Lighting'],['visualStyle','Visual style'],['pacing','Pacing'],['sceneOrder','Scene order'],['actions','Major actions'],['hook','Hook structure'],['demonstration','Demonstration structure'],['cta','CTA structure'],['textOverlays','Text overlays']]
const changeOptions=['Product','Creator','Background','Outfit','Script','Voiceover','Visual style']
export const newRemix = () => ({editMode:'product_swap',sourceAssetId:null,preparedAssetId:null,audioAssetId:null,images:[],keep:['Camera movement','Timing / pacing','Scene order','Creator','Background','Lighting style'],change:['Product'],instructions:'',transcript:'',script:'',scriptApproved:false,observations:'',analysis:null})
const url = a => apiBase()+(a.relative_path==='mock-video-output.mp4'?'/':'/media/')+a.relative_path.split('/').map(encodeURIComponent).join('/')
const aliasList = images => {const n={};return images.map(a=>{const label=a.role==='APP_SCREEN'?'AppScreen':a.role[0]+a.role.slice(1).toLowerCase();n[label]=(n[label]||0)+1;return `@${label}${n[label]>1?n[label]:''}`})}
export function RemixComparison({original,output,onDownload,busy=false}) {
  const left=useRef(null),right=useRef(null),[muted,setMuted]=useState(true),[error,setError]=useState('')
  return <section className="remix-comparison"><h4>Original vs Remix</h4><div className="remix-video-pair">
    <div><strong>Original reference</strong>{original?<video ref={left} src={url(original)} controls muted={muted} playsInline preload="metadata"/>:<p>Choose a reference video.</p>}</div>
    <div><strong>Remix</strong>{output?<video ref={right} src={url(output)} controls muted={muted} playsInline preload="metadata"/>:<p>Your remixed scene will appear here.</p>}</div>
  </div>{output&&<div className="cg-actions"><button className="ghost" onClick={async()=>{setError('');try{for(const v of [left.current,right.current].filter(Boolean)){v.currentTime=0;await v.play()}}catch{setError('Playback could not start. Use the video controls.')}}}>Restart / play both</button><button className="ghost" onClick={()=>setMuted(!muted)}>{muted?'Unmute comparison':'Mute comparison'}</button><button className="ghost" disabled={busy} onClick={()=>onDownload(output)}>Download remix</button></div>}{error&&<p role="alert">{error}</p>}</section>
}
export function ReuseRemixScene({creatives,currentCreativeId,productId,locked,onReuse}) {
  const [target,setTarget]=useState(''),[title,setTitle]=useState('')
  return <details><summary>Use in another Creative</summary><p>Reuse this completed video as a scene. No generation or media copy.</p><label className="field">Destination Creative<select aria-label="Destination Creative" disabled={locked} value={target} onChange={e=>setTarget(e.target.value)}><option value="">New Creative for this product</option>{creatives.filter(c=>String(c.product_test_id)===String(productId)&&String(c.id)!==String(currentCreativeId)).map(c=><option key={c.id} value={c.id}>{c.angle}</option>)}</select></label>{!target&&<label className="field">New remix Creative title<input aria-label="New remix Creative title" value={title} disabled={locked} maxLength={300} onChange={e=>setTitle(e.target.value)}/></label>}<button className="ghost" disabled={locked||(!target&&!title.trim())} onClick={()=>onReuse(target?{targetCreativeId:Number(target)}:{newCreativeTitle:title})}>Add remix to Creative</button></details>
}
export default function ReferenceRemix({scene,options,locked,onChange,act,request,refreshOptions,creativeId,onSegments}) {
  const r=scene.remix || newRemix(),[start,setStart]=useState(r.analysis?.start || 0),[end,setEnd]=useState(r.analysis?.end ?? ''),[imageChoice,setImageChoice]=useState(''),[role,setRole]=useState('PRODUCT')
  const [analyzing,setAnalyzing]=useState(false),[analysisError,setAnalysisError]=useState('')
  const update=(patch,scenePatch={})=>onChange({...scene,...scenePatch,remix:{...r,...patch,scriptApproved:patch.scriptApproved ?? false,promptContext:patch.promptContext ?? (Object.keys(patch).some(k=>k!=='scriptApproved')?'':r.promptContext)}})
  const media=id=>options.media.find(a=>a.id===Number(id)),aliases=aliasList(r.images)
  const prepareSource=async(id,range={start:0})=>{
    const sourceAssetId=Number(id)||null
    setAnalysisError('');setAnalyzing(Boolean(sourceAssetId))
    if (!sourceAssetId) {update({sourceAssetId:null,preparedAssetId:null,analysis:null});return}
    try {
      const result=await request('/api/operator/references/analyze',{assetId:sourceAssetId,...range})
      await refreshOptions();setStart(result.analysis.start);setEnd(result.analysis.end)
      update({sourceAssetId,analysis:result.analysis,preparedAssetId:result.analysis.preparedAssetId})
    } catch(error) {
      update({sourceAssetId,preparedAssetId:null,analysis:null})
      setAnalysisError(error.message || 'Reference preparation failed.')
    } finally {setAnalyzing(false)}
  }
  const setSource=id=>act(async()=>{setStart(0);setEnd('');await prepareSource(id)})
  const upload=(file,kind)=>act(async()=>{
    if(!file)return
    const extension=file.name.split('.').pop().toLowerCase(),mime=file.type || ({mov:'video/quicktime',mp3:'audio/mpeg',wav:'audio/wav'}[extension])
    const response=await fetch(apiBase()+'/api/operator/references/upload',{method:'POST',headers:{'Content-Type':mime},body:file})
    const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'Reference upload failed.')
    if(result.kind!==kind)throw new Error('Choose the requested reference file type.')
    if(kind!=='video')await request('/api/operator/references/validate',{assetId:result.asset.id,kind})
    await refreshOptions()
    if(kind==='video'){setStart(0);setEnd('');await prepareSource(result.asset.id)}
    else if(kind==='image')update({images:[...r.images,{assetId:result.asset.id,role}]})
    else update({audioAssetId:result.asset.id})
  })
  const analyze=()=>act(()=>prepareSource(r.sourceAssetId,{start:Number(start),...(end!==''?{end:Number(end)}:{})}))
  const build=()=>act(async()=>{const result=await request(`/api/operator/generator/${creativeId}/remix-prompt`,{scene});update({script:result.script,promptContext:result.promptContext},{prompt:result.prompt})})
  const toggle=(field,value)=>update({[field]:r[field].includes(value)?r[field].filter(v=>v!==value):[...r[field],value]})
  const beats=r.analysis?.beats || []
  return <div className="reference-remix" data-testid="reference-remix-editor">
    <p className="remix-intro">Reference video, visual references, one instruction.</p>
    <p className="note">Use reference media you are authorized to use. Exact preservation is model-dependent.</p>
    <div className="remix-mode-pills" role="group" aria-label="Remix mode shortcuts">
      {remixModes.map(([id,label])=><button key={id} type="button" className="ghost small" aria-pressed={r.editMode===id} disabled={locked} onClick={()=>{const change={product_swap:['Product'],character_swap:['Creator'],background_swap:['Background'],outfit:['Outfit'],motion_transfer:['Product','Creator','Background'],full_remix:['Product','Script','Voiceover']}[id];update({editMode:id,change,keep:keepOptions.filter(k=>!change.includes(k))})}}>{label}</button>)}
    </div>
    <label className="field remix-mode-select">Mode<select aria-label="Remix mode" disabled={locked} value={r.editMode} onChange={e=>{const mode=e.target.value;const change={product_swap:['Product'],character_swap:['Creator'],background_swap:['Background'],outfit:['Outfit'],motion_transfer:['Product','Creator','Background'],full_remix:['Product','Script','Voiceover']}[mode];update({editMode:mode,change,keep:keepOptions.filter(k=>!change.includes(k))})}}>{remixModes.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>
    <div className="remix-input-grid">
      <div className="subpanel remix-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!locked)upload(e.dataTransfer.files[0],'video')}}><h4>Reference video</h4><p>Drop an MP4 / MOV, or choose one from Assets. We prepare the first 15 seconds locally.</p><label className="field">Upload reference video<input type="file" accept="video/mp4,video/quicktime,.mov" disabled={locked} onChange={e=>upload(e.target.files[0],'video')}/></label><label className="field">Reference video from Media Library<select aria-label="Reference video from Media Library" disabled={locked} value={r.sourceAssetId||''} onChange={e=>setSource(e.target.value)}><option value="">Choose a local reference</option>{options.media.filter(a=>/^video\//.test(a.mime_type)).map(a=><option key={a.id} value={a.id}>{a.relative_path.split('/').pop()}</option>)}</select></label>{r.sourceAssetId&&<small>Original preserved locally</small>}{analyzing?<p role="status">Preparing reference…</p>:r.analysis?<p role="status">Ready · {r.analysis.metadata.duration.toFixed(2)}s · {r.analysis.metadata.width}×{r.analysis.metadata.height}<br/><small>Using {r.analysis.start}–{r.analysis.end}s of the original.</small></p>:null}{!analyzing&&r.sourceAssetId&&!r.analysis&&<div role="alert"><p>{analysisError || 'Reference preparation is incomplete.'} No generation has started.</p><button className="ghost" disabled={locked} onClick={analyze}>Retry reference preparation</button></div>}</div>
      <div className="subpanel"><h4>Reference images</h4><label className="field">Role for next image<select aria-label="Role for next image" value={role} disabled={locked} onChange={e=>setRole(e.target.value)}>{roles.map(v=><option key={v}>{v}</option>)}</select></label><label className="field">Upload reference image<input type="file" accept="image/png,image/jpeg,image/webp" disabled={locked||r.images.length>=9} onChange={e=>upload(e.target.files[0],'image')}/></label><label className="field">Reference image from Media Library<select aria-label="Reference image from Media Library" disabled={locked||r.images.length>=9} value={imageChoice} onChange={e=>setImageChoice(e.target.value)}><option value="">Choose a local image</option>{options.media.filter(a=>a.mime_type.startsWith('image/')&&!r.images.some(ref=>ref.assetId===a.id)).map(a=><option key={a.id} value={a.id}>{a.relative_path.split('/').pop()}</option>)}</select></label><button className="ghost" disabled={locked||!imageChoice||r.images.length>=9} onClick={()=>act(async()=>{await request('/api/operator/references/validate',{assetId:Number(imageChoice),kind:'image'});update({images:[...r.images,{assetId:Number(imageChoice),role}]});setImageChoice('')})}>Add selected reference</button><small>Up to 9 images · PNG/JPEG/WebP · under 30 MB each</small></div>
    </div>
    <div className="remix-reference-cards">{r.images.map((ref,i)=><div className="subpanel" key={ref.assetId}>{media(ref.assetId)&&<img src={url(media(ref.assetId))} alt={`${aliases[i]} reference`}/>}<strong>{aliases[i]}</strong><label className="field">Reference {i+1} role<select aria-label={`Reference ${i+1} role`} disabled={locked} value={ref.role} onChange={e=>update({images:r.images.map((a,n)=>n===i?{...a,role:e.target.value}:a)})}>{roles.map(v=><option key={v}>{v}</option>)}</select></label><button className="ghost small" disabled={locked} onClick={()=>update({images:r.images.filter((_,n)=>n!==i)})}>Remove reference {i+1}</button></div>)}</div>
    <label className="field">What should change?<textarea aria-label="What should change?" rows={4} disabled={locked} value={r.instructions} placeholder="Replace the suitcase with my black suitcase. Keep the same woman, camera movement, room and pacing." onChange={e=>update({instructions:e.target.value})}/></label>
    <details className="remix-advanced"><summary>Advanced / View Analysis</summary>
    <details><summary>Optional audio reference</summary><label className="field">Upload reference audio<input type="file" accept="audio/mpeg,audio/wav,.mp3,.wav" disabled={locked} onChange={e=>upload(e.target.files[0],'audio')}/></label><label className="field">Audio from Media Library<select disabled={locked} value={r.audioAssetId||''} onChange={e=>act(async()=>{const id=Number(e.target.value);if(id)await request('/api/operator/references/validate',{assetId:id,kind:'audio'});update({audioAssetId:id||null})})}><option value="">No audio reference</option>{options.media.filter(a=>a.mime_type.startsWith('audio/')).map(a=><option key={a.id} value={a.id}>{a.relative_path.split('/').pop()}</option>)}</select></label><small>One MP3/WAV · up to 15 seconds · under 15 MB. Audio generation is controlled separately below.</small></details>
    <section className="subpanel"><h4>Reference analysis</h4><div className="cg-controls"><label className="field">Reference start (seconds)<input type="number" min="0" step="0.1" disabled={locked} value={start} onChange={e=>setStart(e.target.value)}/></label><label className="field">Reference end (seconds)<input type="number" min="2" step="0.1" placeholder="First 15 seconds" disabled={locked} value={end} onChange={e=>setEnd(e.target.value)}/></label><button className="ghost" disabled={locked||!r.sourceAssetId} onClick={analyze}>Analyze reference</button></div><small>Free local analysis. Original stays untouched; an optimized reference clip is saved in the Media Library.</small>
      {r.analysis&&<><p>{r.analysis.metadata.duration.toFixed(2)}s · {r.analysis.metadata.width}×{r.analysis.metadata.height} · {(r.analysis.metadata.width/r.analysis.metadata.height).toFixed(2)} aspect · {r.analysis.metadata.frameRate || 'Unknown'} fps · {r.analysis.metadata.audio?'Audio present':'No audio'}</p><p>Prepared input: {r.analysis.preparedMetadata.duration.toFixed(2)}s ({r.analysis.start}–{r.analysis.end}s of original)</p><div className="remix-frames">{r.analysis.frames.map(f=><figure key={f.assetId}><img src={url(f)} alt={`Reference at ${f.time.toFixed(1)} seconds`}/><figcaption>{f.time.toFixed(1)}s</figcaption></figure>)}</div><p className="note">{r.analysis.notes}</p><h4>Editable beat timeline</h4>{beats.map((b,i)=><div className="remix-beat" key={i}><label className="field">Start<input type="number" step="0.1" value={b.start} disabled={locked} onChange={e=>update({analysis:{...r.analysis,beats:beats.map((v,n)=>n===i?{...v,start:Number(e.target.value)}:v)}})}/></label><label className="field">End<input type="number" step="0.1" value={b.end} disabled={locked} onChange={e=>update({analysis:{...r.analysis,beats:beats.map((v,n)=>n===i?{...v,end:Number(e.target.value)}:v)}})}/></label><label className="field">Beat / creative mechanism<input value={b.label} disabled={locked} placeholder="Hook, demonstration, reaction, CTA" onChange={e=>update({analysis:{...r.analysis,beats:beats.map((v,n)=>n===i?{...v,label:e.target.value}:v)}})}/></label><label className="field">Beat description<input value={b.description} disabled={locked} onChange={e=>update({analysis:{...r.analysis,beats:beats.map((v,n)=>n===i?{...v,description:e.target.value}:v)}})}/></label></div>)}<button className="ghost" disabled={locked||beats.length>=24} onClick={()=>update({analysis:{...r.analysis,beats:[...beats,{start:0,end:r.analysis.metadata.duration,label:'New creative beat',description:''}]}})}>Add beat</button></>}
      <details><summary>Structured creative analysis · editable</summary><p>Review the frames and fill what you can identify. These are your observations, not automatic vision results.</p><div className="remix-input-grid">{analysisFields.map(([key,label])=><label className="field" key={key}>{label}<textarea aria-label={`Analysis: ${label}`} rows={2} maxLength={500} disabled={locked} value={r.creativeAnalysis?.[key] || ''} onChange={e=>update({creativeAnalysis:{...r.creativeAnalysis,[key]:e.target.value}})}/></label>)}</div></details><label className="field">Observed subjects, product, environment & creative structure<textarea rows={3} disabled={locked} value={r.observations} placeholder="Review frames: hook structure, demonstration, tone, camera / framing, motion, visual style, visible text and CTA. These observations are operator-authored." onChange={e=>update({observations:e.target.value})}/></label>
    </section>
    <section className="subpanel"><h4>Keep / Change guidance</h4><div className="remix-input-grid"><fieldset><legend>KEEP · guidance</legend>{keepOptions.map(v=><label className="cg-check" key={v}><input type="checkbox" checked={r.keep.includes(v)} disabled={locked} onChange={()=>toggle('keep',v)}/>{v}</label>)}</fieldset><fieldset><legend>CHANGE · guidance</legend>{changeOptions.map(v=><label className="cg-check" key={v}><input type="checkbox" checked={r.change.includes(v)} disabled={locked} onChange={()=>toggle('change',v)}/>{v}</label>)}</fieldset></div><small>Available aliases: @ReferenceVideo{aliases.length?', '+aliases.join(', '):''}. No provider syntax needed.</small></section>
    <section className="subpanel"><h4>Script & generation prompt</h4><p>Optional: edit the script or add observations. The local builder prepares the prompt automatically from your instruction and references. Transcription and semantic vision are not automatic.</p><label className="field">Original Transcript<textarea aria-label="Original Transcript" rows={3} disabled={locked} value={r.transcript} onChange={e=>update({transcript:e.target.value})} placeholder="Optional manual transcript. Not automatically copied into the generation prompt."/></label><button className="ghost" disabled={locked||!r.analysis} onClick={build}>Build adapted script & prompt</button><label className="field">Adapted Script<textarea aria-label="Adapted Script" rows={5} disabled={locked} value={r.script} onChange={e=>update({script:e.target.value})}/></label><p>{scene.generateAudio?'Audio on: the adapted script supplies dialogue guidance.':'Audio off: the script is for planning, captions or later voiceover; no spoken dialogue is requested.'}</p><button className="ghost" disabled={locked||!r.script.trim()} onClick={()=>onSegments()}>Split script into linked segments</button><small>Longer ad: editable segments share references; approve and generate each, then assemble below. Visual continuity is guidance, not guaranteed.</small><details><summary>Advanced Prompt · editable</summary><label className="field">Seedance reference prompt<textarea rows={8} disabled={locked} value={scene.prompt} onChange={e=>update({}, {prompt:e.target.value})}/></label><small>Reference mapping is prepared automatically. Direct edits here are retained until reference guidance, script or audio changes.</small></details><small>Changes save automatically. Generate opens a fresh cost confirmation before any paid request.</small></section>
    </details>
  </div>
}
